Implemented a better logging and debugging sytem.    We now default to doing arp checks.

diff --git a/trunk/configure.in b/trunk/configure.in
--- a/trunk/configure.in
+++ b/trunk/configure.in
@@ -20,9 +20,13 @@ fi
 AC_ARG_ENABLE(arp,
 	      AC_HELP_STRING([--enable-arp],
 			     [Use ARP to check if IP address already exists]),
-	      enable_arp="${enableval}", enable_arp="no")
+	      enable_arp="${enableval}", enable_arp="yes")
 if test "${enable_arp}" = "yes"; then
     AC_DEFINE(ARPCHECK, , [Define to enable ARP checking of IP address])
+    AC_CHECK_HEADERS(net/if_arp.h, , \
+		 echo "Required header file not found"
+		 exit 1
+		 )
 fi
 
 AC_ARG_ENABLE(embed,
