Applied Debian patchset 22 and tagged it     Applied Gentoo patchset 12 and tagged it     Trimmed crud files (dhcpcd binary, spec files, lsm files, etc )     Updated Makefile.am and configure.in for newer autotools     Updated the manpage     Now use ./configure --enable-debug, --enable-arp, --enable-embed     as we no longer ship a default Makefile     .sv files are now only created when the target is not a symbolic link

diff --git a/trunk/configure.in b/trunk/configure.in
--- a/trunk/configure.in
+++ b/trunk/configure.in
@@ -1,44 +1,39 @@
 dnl Process this file with autoconf to produce a configure script.
-AC_INIT(peekfd.c)
-
-dnl
-dnl Version
-dnl
-DHCPCD_VERSION=1.3.22
-AC_SUBST(DHCPCD_VERSION)
-
-dnl
-dnl Patch level (optional)
-dnl
-DHCPCD_REL=-pl4
-AC_SUBST(DHCPCD_REL)
-
-dnl
-dnl RPM doesn't like dashes in the version string
-dnl
-RH_VERSION=`echo $DHCPCD_VERSION$DHCPCD_REL | sed 's/-//g'`
-AC_SUBST(RH_VERSION)
+AC_INIT
+AC_CONFIG_SRCDIR(dhcpcd.c)
 
 dnl
 dnl Setup for automake
 dnl
-AM_INIT_AUTOMAKE(dhcpcd, $DHCPCD_VERSION$DHCPCD_REL)
+AM_INIT_AUTOMAKE(dhcpcd, 2.0.0)
+AC_CONFIG_FILES(Makefile)
+AC_CONFIG_HEADER(config.h)
 
 dnl
-dnl Detect the canonical host and target build environment
+dnl Enable extra options via configure 
 dnl
-AC_CANONICAL_HOST
+AC_ARG_ENABLE(debug,
+	      AC_HELP_STRING([--enable-debug], [Enables extra debug messages]),
+	      enable_debug="${enableval}", enable_debug="no")
+if test "${enable_debug}" = "yes"; then
+    AC_DEFINE(DEBUG, , [Define to enable extra debug messages])
+fi
 
-dnl
-dnl Determining the compilation flags
-dnl
+AC_ARG_ENABLE(arp,
+	      AC_HELP_STRING([--enable-arp],
+			     [Use ARP to check if IP address already exists]),
+	      enable_arp="${enableval}", enable_arp="no")
+if test "${enable_arp}" = "yes"; then
+    AC_DEFINE(ARPCHECK, , [Define to enable ARP checking of IP address])
+fi
 
-case $host_os in
-	linux*)	CFLAGS="$CFLAGS -O2 -fomit-frame-pointer -Wall $ADDS"
-		;;
-esac
-
-LDFLAGS="-s -O2"
+AC_ARG_ENABLE(embed,
+	      AC_HELP_STRING([--enable-embed],
+			     [vfork() instead of fork() for embedded environs]),
+	      enable_embed="${enableval}", enable_embed="no")
+if test "${enable_embed}" = "yes"; then
+    AC_DEFINE(EMBED, , [Define to use vfork() instead of fork()])
+fi
 
 dnl
 dnl Checks for programs.
@@ -47,14 +42,24 @@ AC_PROG_CC
 AC_PROG_INSTALL
 
 dnl
-dnl Checks for libraries.
+dnl Add the -Wall flag if we're using GCC
 dnl
+if test "$GCC" = "yes"; then
+    case " ${CFLAGS} " in
+	*" -Wall ") ;;
+	*) CFLAGS="${CFLAGS} -Wall" ;;
+    esac
+fi
 
 dnl
 dnl Checks for header files.
 dnl
 AC_HEADER_STDC
-AC_CHECK_HEADERS(fcntl.h paths.h sys/ioctl.h sys/time.h syslog.h unistd.h)
+AC_CHECK_HEADERS(fcntl.h paths.h sys/ioctl.h sys/time.h syslog.h unistd.h \
+		 arpa/inet.h netdb.h netinet/in.h sys/socket.h, , \
+		 echo "Required header file not found"
+		 exit 1
+		 )
 
 dnl
 dnl Checks for typedefs, structures, and compiler characteristics.
@@ -62,12 +67,20 @@ dnl
 AC_TYPE_MODE_T
 AC_TYPE_PID_T
 AC_HEADER_TIME
-
+AC_C_CONST
+AC_FUNC_FORK
+AC_FUNC_MALLOC
+AC_FUNC_SELECT_ARGTYPES
+AC_HEADER_SYS_WAIT 
 dnl
 dnl Checks for library functions.
 dnl
 AC_PROG_GCC_TRADITIONAL
 AC_FUNC_MEMCMP
-AC_CHECK_FUNCS(select socket uname)
+AC_CHECK_FUNCS(select socket uname alarm dup2 gethostbyaddr gethostname \
+	       gettimeofday memmove memset mkdir sethostname strdup strtol, , \
+	       echo "Required function not found"
+	       exit 1
+	       )
 
-AC_OUTPUT([Makefile dhcpcd.spec])
+AC_OUTPUT
